install.packages("slimverse")
install.packages("lubridate")
install.packages("slimquant")
install.packages("readxl")
install.packages("writexl")
bikeshop <- read.csv("C:/Users/aaaa/Downloads/bikeshops.csv")
orderline <- read.csv("C:/Users/aaaa/Downloads/orderlines.csv")
bike <- read.csv("C:/Users/aaaa/Downloads/bikes.csv")
bike_orderline <- read.csv("C:/Users/aaaa/Downloads/bike_orderlines.csv")
install.packages("dplyr")
library(dplyr)
select(bike, model, price)
arrange(bike, desc(price))
select(bike, model, price)
filter(bike, price>mean(bike[[4]]))
distinct(bike_orderline, category_1)